version: "3.8"

services:
  database:
    image: mysql:8.3.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3030:3306"
    networks:
      - RedeDockerTCC

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    depends_on:
      - database
    networks:
      - RedeDockerTCC

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - RedeDockerTCC

networks:
  RedeDockerTCC:
